server:
  port: 8096

spring:
  application:
    name: ProductQueryService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productQuery
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin