server:
  port: 8097

spring:
  application:
    name: StockCommandService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stockCommand
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin